apiVersion: v1
kind: ConfigMap
metadata:
  name: dispatcher-config
  namespace: {{ .Values.environment }}
data:
{{- range $plugin, $conf := .Values.plugins -}}
  {{- if $conf.enabled }}
  {{$plugin}}_data_server_conf.yml: |
    instruments:
      {{- toYaml $conf.instruments | nindent 6 }}
  {{- end }}
{{- end -}}