apiVersion: v1
kind: ConfigMap
metadata:
  name: dispatcher-config
  namespace: {{ .Values.environment }}
data:
  osa_data_server_conf.yml: |
    instruments:
      isgri:
          dispatcher_mnt_point: /data
          data_server_cache: reduced/ddcache
          dummy_cache: /data/dummy_prods
          data_server_url: dda-interface
          data_server_port: 8000

      jemx:
          dispatcher_mnt_point: /data
          data_server_cache: reduced/ddcache
          dummy_cache: /data/dummy_prods
          data_server_url: 
          data_server_url: dda-interface
          data_server_port: 8000

