apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
spec:
  storageClassName: {{ .Values.storage_class }}
  accessModes:
    - ReadWriteOnce
      #- ReadWriteMany
  resources:
    requests:
      storage: 10Gi


{{ if not (default false .Values.use_hostpath) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dispatcher-scratch-root
spec:
  storageClassName: {{ .Values.storage_class }} 
  accessModes:
    - ReadWriteOnce
      #- ReadWriteMany
  resources:
    requests:
      storage: 30Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dispatcher-filelogdir
spec:
  storageClassName: {{ .Values.storage_class }} 
  accessModes:
    - ReadWriteOnce
      #- ReadWriteMany
  resources:
    requests:
      storage: 30Gi
---
# PersistentVolumeClaims related to dda and ddcache should be defined only in dda, since they are useless in the dispatcher if dda is not deployed

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-reduced-ddcache
spec:
  storageClassName: {{ .Values.storage_class }} 
  accessModes:
    - ReadWriteOnce
      #- ReadWriteMany
  resources:
    requests:
      storage: 30Gi
---

{{ end }}
